name = "shahnama-transcription"
compatibility_date = "2024-07-18"
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
NODE_VERSION = "22"
PNPM_VERSION = "9"

[[d1_databases]]
binding = "AUTH_DB"
database_name = "transcription-auth-alpha3"
database_id = "4c780188-e0fd-4860-874d-70eafaa278a2"
