name = "shahnama-transcription"
compatibility_date = "2024-07-18"
pages_build_output_dir = ".svelte-kit/cloudflare"

compatibility_flags = ["nodejs_compat"]

[vars]
NODE_VERSION = "22"

[[d1_databases]]
binding = "AUTH_DB"
database_name = "transcription-auth-alpha-2"
database_id = "8c20eab1-92ae-40a5-bb0e-f8bbaada27ab"
