name = "shahnama-transcription"
compatibility_date = "2026-04-06"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
NODE_VERSION = "24"
PNPM_VERSION = "10"

[[d1_databases]]
binding = "DB"
database_name = "transcription-alpha2"
database_id = "984da4a9-d00d-49a1-a12e-acff27bbf05c"
