name = "shahnama-transcription"
compatibility_date = "2024-07-18"
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
NODE_VERSION = "22"
PNPM_VERSION = "9"

[[d1_databases]]
binding = "DB"
database_name = "transcription-alpha2"
database_id = "984da4a9-d00d-49a1-a12e-acff27bbf05c"
